server:
  port: 8761

spring:
  application:
    name: eureka-server

  # le dice que busque su config en el config-server
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    hostname: localhost
  client:
    # eureka no se registra a sí mismo
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0   # arranca más rápido en dev